packages:
  - apps/*
  - packages/*
  - internal/*

catalog:
  "@antfu/eslint-config": ^5.2.1
  "@eslint/js": ^9.33.0
  "@iconify-json/tabler": ^1.2.22
  "@iconify/vue": ^5.0.0
  "@tailwindcss/postcss": ^4.1.11
  "@tailwindcss/vite": ^4.1.11
  "@tsconfig/node22": ^22.0.2
  "@types/eslint": ^9.6.1
  "@types/mockjs": ^1.0.10
  "@types/node": ^24.2.1
  "@types/qs": ^6.14.0
  "@typescript-eslint/eslint-plugin": ^8.40.0
  "@typescript-eslint/parser": ^8.40.0
  "@vitejs/plugin-vue": ^6.0.1
  "@vitejs/plugin-vue-jsx": ^5.0.1
  "@vue/eslint-config-typescript": ^14.6.0
  "@vueuse/core": ^13.6.0
  axios: ^1.11.0
  colord: ^2.9.3
  dayjs: ^1.11.13
  dotenv: ^17.2.1
  es-toolkit: ^1.39.9
  eslint: ^9.33.0
  eslint-config-turbo: ^2.5.6
  eslint-plugin-command: ^3.3.1
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-import: ^2.32.0
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-jsdoc: ^54.1.0
  eslint-plugin-jsonc: ^2.20.1
  eslint-plugin-n: ^17.21.3
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^4.15.0
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-promise: ^7.2.1
  eslint-plugin-regexp: ^2.10.0
  eslint-plugin-unicorn: ^60.0.0
  eslint-plugin-unused-imports: ^4.2.0
  eslint-plugin-vitest: ^0.5.4
  eslint-plugin-vue: ^10.4.0
  globals: ^16.3.0
  jiti: ^2.5.1
  jsonc-eslint-parser: ^2.4.0
  mockjs: ^1.1.0
  naive-ui: ^2.42.0
  npm-run-all2: ^8.0.4
  pinia: ^3.0.3
  pinia-plugin-persistedstate: ^4.5.0
  postcss: ^8.5.6
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  qs: ^6.14.0
  tailwindcss: ^4.1.11
  tsup: ^8.5.0
  turbo: ^2.5.6
  tw-animate-css: ^1.3.6
  typescript: ^5.9.2
  unbuild: ^3.6.1
  unplugin-auto-import: ^20.0.0
  unplugin-icons: ^22.2.0
  unplugin-vue-components: ^29.0.0
  vite: ^7.1.2
  vite-plugin-compression: ^0.5.1
  vite-plugin-dts: ^4.5.4
  vite-plugin-image-optimizer: ^2.0.2
  vite-plugin-mock: ^3.0.2
  vite-plugin-progress: ^0.0.7
  vite-plugin-vue-devtools: ^8.0.0
  vite-plugin-vue-setup-extend: ^0.4.0
  vite-svg-loader: ^5.1.0
  vue: ^3.5.18
  vue-draggable-plus: ^0.6.0
  vue-eslint-parser: ^10.2.0
  vue-i18n: ^11.1.11
  vue-router: ^4.5.1
  vue-tsc: ^3.0.5
